version: "3.7"
services:
  web:
    build: app
    links:
      - otel-collector
    environment:
      # Configure Open Telemetry Collector Url
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      DD_SERVICE: "sanic-otel"
    volumes:
      - ./app/src/server.py:/code/server.py  
    ports:
      - "5000:5000"
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.19.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      DD_ENV: "otel"
      DD_SERVICE: "sanic-otel"
      DD_VERSION: "6"
      DD_API_KEY: ${DD_API_KEY}
      HOSTNAME: "macbook-willian"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"        # OTLP gRPC receiver