receivers:
  hostmetrics:
    scrapers:
      load:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      paging:
      process:    
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s
  resource:
    attributes:
    - key: datadog.host.name
      value: ${HOSTNAME}
      action: upsert
    
exporters:
  datadog/api: 
    hostname: ${HOSTNAME}
    env: ${DD_ENV}
    service: ${DD_SERVICE}
    version: 3
    tags:
      - service:${DD_SERVICE}
      - env:${DD_ENV}
    api:
      key: ${DD_API_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [datadog/api]
    metrics:
      receivers: [hostmetrics]
      processors: [resource, batch]
      exporters: [datadog/api]
#    logs:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [datadog/api]
