version: "3.7"
services:
  web:
    build: app
    links:
      - datadog-agent
    environment:
      DD_SERVICE: "sanic-datadog"
      DD_AGENT_HOST: "datadog-agent"
    volumes:
      - ./app/src/server.py:/code/server.py  
    ports:
      - "5010:5000"
    depends_on:
      - datadog-agent

  datadog-agent:
    image: "datadog/agent"
    container_name: agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS=env:otel
      - DD_LOG_LEVEL=WARN
      - DD_HOSTNAME=datadog-collector
    ports:
      - "8126:8126"
      - "8125:8125"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro